spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true
    username: root
    password: abc1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
  properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

